### ISSUE TITLE
What about multiple redshift clusters??

### ISSUE THREAD

**Issue by cavanaug** [llooker/blocks_redshift_admin#32]
What would be the recommended model to use here if your looker system connects to multiple redshift clusters??

Is there some preferred way to namespace things so that this could be used on one looker instance with multiple tenants (in essence).

**Comment by fabio-looker** [comment]
Hi, thanks for the question. There are two options I can think of:

1) I already recommend keeping the Redshift block in its own project, as there is little if any need to join this dataset to other tables in your models. So, you can put all the explore definitions in a .explore.lkml file, make one connection & one model per cluster, and then include the explores, views, and dashboards into each of those models.

2) Since you mentioned tenancy, could it be the case that most users only need to see one cluster? If so, then you could try something with parameterized connections. The only problem is that PDTs are only partially supported with parameterized connections, and won't work for this case. If you can move those tables to an ETL process, this could work.
